### ISSUE TITLE
Testing with hybrid coordinates show spikes in surface pCO2 - problem in Bothnian Sea?

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#390] opened 2024-09-06 07:45 UTC
There is a problem with the hybrid model run as seen in pCO2 time series. This can be traced down to the Bothnian Sea, where a couple of grid points have (annual mean) pCO2 that reaches several 10 000 mu atm. One observation that could be related is that the layer thickness in this region is very large: The top layer is >30 m as opposed to almost everywhere else where it is around 2.5 m. The 2-degree hybrid run is generally relatively noisy (given the normal year forcing) and there seem to be occasional convection(?) events in the Southern Ocean (best seen in CO2- and O2-fluxes).

Diagnostics: https://ns2345k.web.sigma2.no/datalake/diagnostics/noresm/jschwing/

Short explanation of runs:
-----------------------------

NOINYOC_T62_tn21_27: CMIP6 version of the model
NOINYOC_T62_tn21_37: Current master (sediment acceleration is switched on by default for 800 years) but increased sediment remineralization of POC (disso_poc = 5.0e-6)
NOINYOC_T62_tn21_38: Same as 37, but increased sediment remineralization of POC (disso_poc = 5.0e-6) AND increased background diffusivity (BDMC2 = 1.2e-5)
NOINYOC_T62_tn21_39: Same as 37, but with extendend N-cycle turned ON
NOINYOC_T62_tn21_40: Same as 39, but with hybrid coordinates turned ON
NOINYOC_T62_tn21_41: Same as 40, but with neutral diffusion turned off

All runs (except the CMIP6 one of course) are based on current master

**Comment by JorgSchwinger** [comment] 2024-09-16 08:01
@matsbn @TomasTorsvik @jmaerz, I have now finished a 200 year hybrid-coordinate NOINYOC run (CORE normal year forcing) on the tnx1v4 grid for comparison with the same configuration on the tnx2v1 grid.

The 1-degree resolution shows in principle the same thing in the northern Baltic, just a bit weaker: There is elevated, noisy pCO2 in the northern Baltic sea, which can be even seen as large spikes in the global time-series (blue is the tnx1v4 grid):

![NorDiag_gts_T62_tn14_40-tn21_40_0001-0200_p09](https://github.com/user-attachments/assets/87e1ed73-5122-42c8-b2ee-4f759e6b588b)
 
Again, one observation is that layer structure in this region is characterized by relatively few layers: a top-layer that is 7-8 metres thick (versus 2.5 metres everywhere else) and a second layer down to the bottom (several 10s of metres). Notably, this is different from the isopycnic model, which had 3 layers in this region.

Another observation is that the surface salinity is less in hybrid (3.3 vs 3.6, the latter being closer observations (~3.7). The output (as well as the output of all 2-degree simulations mentioned above) is here:

/projects/NS2980K/schwinger/NOINYOC_T62_tn14_40

**Comment by JorgSchwinger** [comment] 2024-12-04 13:28
@matsbn @TomasTorsvik @jmaerz 

Update:

I have now run a test with the modifications introduced in #432. The layer structure in the Baltic sea is now much improved. Where before only two layers were present (a ~2.5 m thick top layer and one layer below) now 4 model layers a maintained throughout the Baltic. 

@matsbn : What is the difference between the model output dp and dzlvl (I mean apart from the units - they seem to represent different quantities)?

The spikes in pCO2 in the global time-series have disappeared (red: old, yellow: new):
 
![NorDiag_gts_T62_tn21_27-tn21_40-tn21_44_0001-0300_p09](https://github.com/user-attachments/assets/e0a04415-0084-4481-a8c7-08ead2aa41f5)

However, there is still a problem with pCO2 (and pH) in the northern Baltic. This can be traced down to our carbonate algorithm becoming unstable in the northern Baltic Sea under very low salinity conditions. Apparently, freshwater here has a large impact with the hybrid coordinate, probably freshwater induced stratification is maintained better(?) . I am working on a fix, which will then eventually close this issue.

**Comment by JorgSchwinger** [comment] 2024-12-04 13:51
@matsbn 

By the way, I was a bit surprised that #432 changes (increases) primary production quite a bit, mainly in the tropics. Globally, this is an increase by ~2 Pg C yr-1 (which is about +5%). See diagnostics here:

https://ns2345k.web.sigma2.no/datalake/diagnostics/noresm/jschwing/NOINYOC_T62_tn21_44/HAMOCC_DIAG/yrs191to200-NOINYOC_T62_tn21_40/set2/set2_ann_ppint_2models.png

So it seems that the changes must also have and effect on tropical layer structure? Is this expected?

**Comment by matsbn** [comment] 2024-12-04 14:22
Thanks for testing, @JorgSchwinger ! Good to see that the spikes in pCO2 in the global time-series have disappeared.

I have not checked carefully the impact of hybrid vertical coordinate and low salinity conditions in marginal seas. I did have an issue with salinity becoming negative in the Baltic Sea with 1/8 deg grid and hybrid coordinate, but then I made a quick non-conservative fix since simulations was not expected to be very long. With tnx1v4 grid, which I mostly tested with, I did not yet encounter such issues, but salinity may have been lower. I hope to look at this more carefully.

Interesting to see the change in primary production in the tropics. I was prepared that some changes could occur in the tropics for situations when water becomes so warm and light that they would be lighter that the reference density of the k = 5 interface. But for temperature and salinity I found very little difference with the https://github.com/NorESMhub/BLOM/pull/432 changes. Maybe it has to with how heat, freshwater and brine fluxes contribute to temperature and salinity tendencies compared to pCO2? With KPP we use so-called nonlocal transport within the surface boundary layer of heat, freshwater and brine fluxes. That might reduce the dependency of the model resolution within the boundary layer. If pCO2 flux only creates tendency in the top layer, there might be a stronger resolution dependency. If this is the case, we should maybe consider to harmonise how BLOM and iHAMOCC incorporates surface fluxes, e.g. that iHAMOCC makes use of the nonlocal transport arrays that BLOM provides.

**Comment by JorgSchwinger** [comment] 2024-12-10 08:37
@matsbn 

> Interesting to see the change in primary production in the tropics. I was prepared that some changes could occur in the tropics for situations when water becomes so warm and light that they would be lighter that the reference density of the k = 5 interface. But for temperature and salinity I found very little difference with the #432 changes.

I can confirm that the changes in the physical ocean are not large and everything looks reasonable. See diagnostics here (NOINYOC_T62_tn21_40 = old; NOINYOC_T62_tn21_44 = new):

https://ns2345k.web.sigma2.no/datalake/diagnostics/noresm/jschwing/NOINYOC_T62_tn21_44/BLOM_DIAG/yrs191to200-NOINYOC_T62_tn21_40/indexnew.html

I suspect that the increased PP in iHAMOCC in the new code is due to a better / more regular vertical resolution maintained close to the surface. A hint towards this is that surface nutrients are LOWER in the new code, so nutrients are used more efficiently rather than driving a higher PP due to larger availability. More efficient nutrient utilization might come from a better representation of the light availability/limitation in the surface due to the better resolution, without this affecting the physical fields so much. These changes are not huge either, so I think this is fine.

All gas-exchange fluxes (CO2, O2, CFCs, ...) in iHAMOCC are only applied into/out of the surface layer. In general, it would be nice to have a consistent treatment of heat and carbon (and all other) fluxes, but it's unclear to me what this would take to implement?

**Comment by JorgSchwinger** [comment] 2024-12-17 09:20
This has been solved by #432 and #446. I close this issue for now.

**Closed as completed by JorgSchwinger** 2024-12-17 09:20 UTC
Labels: bug
